version: '3.0'
services:
  db:
    image: postgres
    container_name: mentoria
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mentoria
    volumes:
      - ./docker/db:/data/postgres